# Generated by Django 2.0.2 on 2018-02-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_auto_20180218_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fathered', to='familytree.FamilyMember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mothered', to='familytree.FamilyMember'),
        ),
    ]
